cities:
  leuven:
    crs_project: 32631
    edges_file: "data/leuven_walk_edges.gpkg"
    sensors_file: "data/leuven_telraam_pedestrians_4326.geojson"
    origins_file: "data/leuven_worldpop_origins.geojson"
    destinations_file: "data/leuven_attractors.geojson"
    worldpop_url: "https://data.worldpop.org/GIS/Population/Global_2000_2020/2020/BEL/bel_ppp_2020.tif"
    worldpop_local_tif: "bel_ppp_2020.tif"
    bbox: [4.6798, 50.8600, 4.7301, 50.9001]
    overpass_bbox: [50.85, 4.66, 50.91, 4.74]
  oxford:
    crs_project: 27700
    edges_file: "data/oxford_walk_edges.gpkg"
    sensors_file: "data/telraam_pedestrians_27700.geojson"
    # To be populated when demand data for Oxford is added
