<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robin Lovelace">
<meta name="dcterms.date" content="2026-08-07">

<title>Benchmarking open-source tools for estimating urban transport flows: walking, cycling and driving</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-ac7bf1d0f0b37a24fbd3e01aa6801bd3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#benchmark-suite-design" id="toc-benchmark-suite-design" class="nav-link" data-scroll-target="#benchmark-suite-design">Benchmark suite design</a></li>
  <li><a href="#tools" id="toc-tools" class="nav-link" data-scroll-target="#tools">Tools</a></li>
  <li><a href="#ground-truth-and-demand" id="toc-ground-truth-and-demand" class="nav-link" data-scroll-target="#ground-truth-and-demand">Ground truth and demand</a></li>
  <li><a href="#metrics-and-the-efficiency-score" id="toc-metrics-and-the-efficiency-score" class="nav-link" data-scroll-target="#metrics-and-the-efficiency-score">Metrics and the efficiency score</a></li>
  <li><a href="#tool-complexity" id="toc-tool-complexity" class="nav-link" data-scroll-target="#tool-complexity">Tool complexity</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#walking-leuven-telraam" id="toc-walking-leuven-telraam" class="nav-link" data-scroll-target="#walking-leuven-telraam">Walking (Leuven, Telraam)</a></li>
  <li><a href="#driving-leeds-dft-aadt" id="toc-driving-leeds-dft-aadt" class="nav-link" data-scroll-target="#driving-leeds-dft-aadt">Driving (Leeds, DfT AADT)</a></li>
  <li><a href="#cycling-coverage-gap-no-per-mode-sensor-data-yet" id="toc-cycling-coverage-gap-no-per-mode-sensor-data-yet" class="nav-link" data-scroll-target="#cycling-coverage-gap-no-per-mode-sensor-data-yet">Cycling (coverage gap — no per-mode sensor data yet)</a></li>
  <li><a href="#efficiency-frontier" id="toc-efficiency-frontier" class="nav-link" data-scroll-target="#efficiency-frontier">Efficiency frontier</a></li>
  <li><a href="#accuracy-versus-complexity" id="toc-accuracy-versus-complexity" class="nav-link" data-scroll-target="#accuracy-versus-complexity">Accuracy versus complexity</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Benchmarking open-source tools for estimating urban transport flows: walking, cycling and driving</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Robin Lovelace </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Urban transport planners increasingly rely on open-source tools to estimate pedestrian, cycle and motor traffic flows on street networks. The tools benchmarked here — cityseer <span class="citation" data-cites="simons2022cityseer">(<a href="#ref-simons2022cityseer" role="doc-biblioref">Simons 2022</a>)</span>, madina <span class="citation" data-cites="sevtsuk2025madina">(<a href="#ref-sevtsuk2025madina" role="doc-biblioref">Sevtsuk and Alhassan 2025</a>)</span>, sDNA <span class="citation" data-cites="cooper2020sdna">(<a href="#ref-cooper2020sdna" role="doc-biblioref">Cooper and Chiaradia 2020</a>)</span>, flownet <span class="citation" data-cites="krantz2024flownet">(<a href="#ref-krantz2024flownet" role="doc-biblioref">Krantz, Dünch, et al. 2024</a>)</span> and aequilibrae <span class="citation" data-cites="aequilibrae2024">(<a href="#ref-aequilibrae2024" role="doc-biblioref">Camargo 2024</a>)</span> — span very different modelling traditions: network centrality and space syntax, gravity and floating-catchment-area demand models, path-sized logit assignment and user-equilibrium traffic assignment. Yet no systematic benchmark has compared these tools against the same observed counts, on the same networks, with the same demand inputs, so evidence-based tool choice remains difficult.</p>
<p>A structural gap motivates this work: most tools belong to the all-or-nothing (AoN) shortest-path family, which assigns each origin–destination pair to a single deterministic route. Only a few implement dispersed or multi-path assignment, spreading flow across several plausible routes via stochastic user equilibrium (SUE), user equilibrium (UE) or path-sized logit (PSL) models. Whether the route-choice model class materially affects predictive performance against real counts is untested, because tools are rarely run side-by-side on common ground-truth data.</p>
<p>This paper addresses three research questions:</p>
<ol type="1">
<li><strong>Does the route-choice model class matter?</strong> Do dispersed and equilibrium assignment models (UE, PSL, dispersion-tolerant OD betweenness) predict observed flows better than the AoN shortest-path baseline?</li>
<li><strong>Does demand realism dominate algorithm sophistication?</strong> Does a real census-derived origin–destination matrix outperform a synthetic gravity model, and does the choice of demand input swamp the choice of assignment algorithm?</li>
<li><strong>Does a composite efficiency score change the rankings?</strong> Runtime and memory requirements vary by orders of magnitude across tools, so any honest comparison must reward accuracy per unit of computational resource — and doing so may reorder the tools relative to an accuracy-only ranking.</li>
</ol>
<p>The benchmark presented here answers these questions with a reproducible suite (DVC pipeline, Docker image, pinned versions) and a single composite metric, the <em>efficiency score</em> (Equation <a href="#eq-efficiency" class="quarto-xref">Equation&nbsp;1</a>). Results are organised by mode — walking (Leuven), driving (Leeds) and cycling (a coverage gap) — and all tables and figures are computed live from the benchmark result files at render time.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="benchmark-suite-design" class="level2">
<h2 class="anchored" data-anchor-id="benchmark-suite-design">Benchmark suite design</h2>
<p>Results were produced by a reproducible benchmark suite, defined as a DVC pipeline (<code>dvc.yaml</code>) with a <code>Dockerfile</code> for containerised reproduction (<code>dvc repro</code> regenerates all stages, and <code>dvc.lock</code> pins the state of every stage). Each tool is run by a dedicated script in <code>scripts/</code> (<code>bench_centrality.py</code>, <code>bench_cityseer_od.py</code>, <code>bench_sdna.py</code>, <code>bench_flownet.py</code>, <code>bench_aequilibrae.py</code>, and the demand-experiment runners <code>run_cityseer_demand_experiments.py</code> and <code>run_madina_demand_experiments.py</code>), driven by shared configuration (<code>config/cities.yaml</code>) and shared metrics helpers (<code>scripts/utils/</code>). Per-tool results are merged into per-city result tables (<code>results/leuven_results.csv</code>, <code>results/leeds_results.csv</code>), which all tables and figures in this paper read directly during rendering.</p>
</section>
<section id="tools" class="level2">
<h2 class="anchored" data-anchor-id="tools">Tools</h2>
<p>Eight tool configurations are compared: <strong>cityseer</strong> (network centrality), <strong>cityseer_demand</strong> (cityseer’s gravity demand model), <strong>cityseer_od</strong> (OD betweenness with configurable dispersion and tolerance), <strong>madina</strong> (topological betweenness and weighted betweenness), <strong>madina_worldpop</strong> (floating-catchment-area gravity with WorldPop demand), <strong>sDNA+</strong> (hybrid centrality), <strong>flownet</strong> (path-sized logit assignment) and <strong>aequilibrae</strong> (all-or-nothing and user-equilibrium assignment).</p>
</section>
<section id="ground-truth-and-demand" class="level2">
<h2 class="anchored" data-anchor-id="ground-truth-and-demand">Ground truth and demand</h2>
<p>Ground truth comprises Leuven Telraam pedestrian counts (walk mode) <span class="citation" data-cites="telraam2024">(<a href="#ref-telraam2024" role="doc-biblioref">Telraam 2024</a>)</span> and Leeds Department for Transport annual average daily traffic (AADT) counts (drive mode) <span class="citation" data-cites="dft2023aadt">(<a href="#ref-dft2023aadt" role="doc-biblioref">Department for Transport 2023</a>)</span>. Demand inputs differ by design: Leeds demand-driven tools are fed a real 2011 Census journey-to-work origin–destination matrix (<code>pct::get_od</code>, MSOA level; used by cityseer_od and aequilibrae), whereas a synthetic gravity demand (WorldPop residential origins × OSM-POI attractors) is used for the gravity-family tools (cityseer_demand, madina_worldpop) and for flownet, and for the Leuven OD runs. Comparing cityseer_od (real OD) with madina_worldpop (synthetic gravity) on the same Leeds network therefore isolates the effect of demand realism on otherwise comparable assignment frameworks.</p>
</section>
<section id="metrics-and-the-efficiency-score" class="level2">
<h2 class="anchored" data-anchor-id="metrics-and-the-efficiency-score">Metrics and the efficiency score</h2>
<p>Predictive performance is measured with R² against observed counts alongside runtime (<code>compute_time_s</code>), peak memory (<code>peak_memory_mb</code>) and throughput (<code>segments_per_sec</code>). Two R² variants are in use: linear R² (<code>compute_metrics</code>) for the centrality and gravity tools, and log-log R² (<code>compute_metrics_loglog</code>) for cityseer_od and aequilibrae, whose flows span orders of magnitude. <strong>R² values from the two variants are not directly comparable</strong> — a point we return to in Limitations. Sample sizes are small: 22 matched Telraam sensors in Leuven and 181–197 matched AADT links in Leeds (where recorded).</p>
<p>To combine accuracy with computational cost we use the composite efficiency score:</p>
<p><span id="eq-efficiency"><span class="math display">\[ \mathrm{efficiency\_score} = \frac{\max(R^2, 0)}{\log_{10}(1 + t) \cdot \log_{10}(1 + m)}  \tag{1}\]</span></span></p>
<p>where <span class="math inline">\(t\)</span> is runtime in seconds and <span class="math inline">\(m\)</span> is peak memory in MB (<a href="#eq-efficiency" class="quarto-xref">Equation&nbsp;1</a>). Code complexity is quantified as lines of code (LoC, non-blank, non-comment) of each tool’s integration script plus its source code.</p>
<p>Leeds is modelled within a 10 km buffer clip around central Leeds (235.7k / 233.2k / 63.9k walk/cycle/drive edges), which introduces a boundary artefact for zone-based dispersion (see Limitations).</p>
</section>
<section id="tool-complexity" class="level2">
<h2 class="anchored" data-anchor-id="tool-complexity">Tool complexity</h2>
<p>Table <a href="#tbl-complexity" class="quarto-xref">Table&nbsp;1</a> quantifies integration effort and codebase size per tool. The integration LoC column counts the benchmark scripts that wrap each tool; the source LoC column counts the tool’s own code, excluding native cores where the tool is a Python binding (cityseer’s Rust core and aequilibrae’s C++ core are deliberately excluded).</p>
<div class="cell" data-execution_count="1">
<div id="tbl-complexity" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-complexity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Code complexity by tool: integration script LoC, tool source LoC and total (non-blank, non-comment lines). cityseer and aequilibrae totals exclude native (Rust/C++) cores.
</figcaption>
<div aria-describedby="tbl-complexity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Tool</th>
<th data-quarto-table-cell-role="th">Integration LoC</th>
<th data-quarto-table-cell-role="th">Tool source LoC</th>
<th data-quarto-table-cell-role="th">Total LoC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>cityseer</td>
<td>1436</td>
<td>8715</td>
<td>10151</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>madina</td>
<td>155</td>
<td>3616</td>
<td>3771</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>sDNA</td>
<td>225</td>
<td>17173</td>
<td>17398</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>flownet</td>
<td>313</td>
<td>1847</td>
<td>2160</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>aequilibrae</td>
<td>339</td>
<td>16248</td>
<td>16587</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<p>The suite is designed to make every number in this paper regenerable:</p>
<ul>
<li><strong>DVC pipeline.</strong> <code>dvc.yaml</code> defines one stage per benchmark (e.g.&nbsp;<code>bench_centrality</code>, <code>bench_cityseer_demand</code>, <code>bench_madina_gravity</code>, <code>bench_sdna</code>, <code>bench_flownet</code>, and the Leeds equivalents <code>bench_cityseer_od_leeds</code>, <code>bench_aequilibrae_leeds</code>), plus data preparation (<code>prepare_demand</code>, <code>prepare_leeds_ground_truth</code>, <code>generate_networks</code>, <code>generate_networks_leeds</code>), the <code>clip_leeds_inputs</code> side-effect stage, result merging (<code>merge_results</code>, <code>merge_results_leeds</code>) and report rendering (<code>render_report</code>). <code>dvc repro</code> from the repository root regenerates every stage; <code>dvc.lock</code> records the hashes of all inputs and outputs.</li>
<li><strong>Docker image.</strong> The multi-stage <code>Dockerfile</code> first builds the sDNA+ C++ library with OpenMP, then installs the Python/R toolchain on <code>ghcr.io/geocompx/python</code> (Python 3.12, Debian Bookworm) and runs <code>dvc repro</code> as the container command: <code>docker build -t cenbench . &amp;&amp; docker run cenbench</code>.</li>
<li><strong>Pinned versions.</strong> cityseer <code>4.24.1</code>, aequilibrae <code>1.7.0</code>, flownet <code>0.3.0</code> (R package), madina (<code>fix-pandas-numpy-compat</code> branch), sDNA+ <code>4.1.1</code> (Cross_platform branch), pandas <code>&gt;=3.0</code>, Quarto <code>1.8.27</code> (pinned in the Dockerfile) and R from the base image. <code>requirements.txt</code> pins the Python stack; the flownet runner is <code>scripts/run_flownet_assignment.R</code>.</li>
<li><strong>Random seeds.</strong> The OD sampling in <code>scripts/bench_cityseer_od.py</code> uses <code>np.random.RandomState(42)</code>; all other runners are deterministic given their inputs.</li>
<li><strong>Ground truth regeneration.</strong> Leeds AADT counts come from <code>scripts/prepare_leeds_ground_truth.py</code>; the census OD matrix and MSOA zones are fetched by <code>scripts/fetch_pct_od.R</code> via <code>pct::get_od</code> (MSOA geography). Leuven Telraam counts are fetched from the Telraam API.</li>
<li><strong>The 10 km clip.</strong> <code>scripts/clip_leeds_inputs.py</code> applies the circular 10 km buffer clip to the Leeds networks, DfT AADT points and PCT zones/OD pairs in place (a side-effect DVC stage), so the clipped inputs are exactly the ones benchmarked.</li>
<li><strong>Efficiency score.</strong> Defined in Equation <a href="#eq-efficiency" class="quarto-xref">Equation&nbsp;1</a>; the merged result CSVs carry a precomputed <code>efficiency_score</code> column using the same formula.</li>
<li><strong>Rendering this paper.</strong> From the <code>paper/</code> directory, with the repository virtualenv active: <code>quarto render index.qmd --to html</code>. All tables and figures are computed at render time from <code>results/</code>, so re-rendering picks up any updated benchmark outputs.</li>
</ul>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>All tables and figures in this section are computed live from <code>results/leuven_results.csv</code> and <code>results/leeds_results.csv</code> at render time, so they always reflect the current benchmark outputs.</p>
<section id="walking-leuven-telraam" class="level2">
<h2 class="anchored" data-anchor-id="walking-leuven-telraam">Walking (Leuven, Telraam)</h2>
<p>Table <a href="#tbl-leuven" class="quarto-xref">Table&nbsp;2</a> reports, for each tool, the best-performing variant by efficiency score on Leuven walk flows.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-leuven" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-leuven-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Best variant per tool by efficiency score — Leuven, walk mode (Telraam ground truth). All eight tools have merged Leuven results. R² rows for cityseer_od and aequilibrae use log-log R²; all other rows use linear R², so values are not directly comparable across rows.
</figcaption>
<div aria-describedby="tbl-leuven-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Tool</th>
<th data-quarto-table-cell-role="th">Best variant</th>
<th data-quarto-table-cell-role="th">R²</th>
<th data-quarto-table-cell-role="th">Time (s)</th>
<th data-quarto-table-cell-role="th">Peak memory (MB)</th>
<th data-quarto-table-cell-role="th">Efficiency score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>cityseer_od</td>
<td>od_dimensionless_imp_k3_tol0.03_r20000</td>
<td>0.1052</td>
<td>0.03</td>
<td>464.9</td>
<td>3.072</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>aequilibrae</td>
<td>aon</td>
<td>0.0845</td>
<td>0.05</td>
<td>301.9</td>
<td>1.606</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>cityseer_demand</td>
<td>cs_demand_r1600_beta002_all</td>
<td>0.6244</td>
<td>2.48</td>
<td>420.0</td>
<td>0.439</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>madina</td>
<td>degree</td>
<td>0.1453</td>
<td>0.72</td>
<td>424.6</td>
<td>0.235</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>madina_worldpop</td>
<td>wp_r3000_beta002_all</td>
<td>0.8758</td>
<td>48.29</td>
<td>300.1</td>
<td>0.209</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>sdna</td>
<td>MAD_angular_800m</td>
<td>0.4676</td>
<td>8.39</td>
<td>400.0</td>
<td>0.185</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>cityseer</td>
<td>shortest_800m</td>
<td>0.0042</td>
<td>0.08</td>
<td>374.2</td>
<td>0.048</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>flownet</td>
<td>psl_beta0.001_detour1.5</td>
<td>0.0092</td>
<td>55.35</td>
<td>402.4</td>
<td>0.002</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Four findings stand out for walk flows:</p>
<ul>
<li><strong>Demand explains pedestrian counts; centrality does not.</strong> The two gravity-demand models lead on accuracy: madina_worldpop (linear R² 0.876) and cityseer_demand (0.676), both sharing the same synthetic WorldPop × POI gravity demand. The pure centrality variants of cityseer, madina and flownet explain almost none of the variance in pedestrian counts (R² 0.004–0.145), and even the best centrality-only tool (sDNA+, 0.468) trails the demand-driven models.</li>
<li><strong>The efficiency score reorders the ranking.</strong> cityseer_od tops Table <a href="#tbl-leuven" class="quarto-xref">Table&nbsp;2</a> (efficiency 3.07) despite an R² of only 0.105 (log-log), because it runs in 0.03 s versus 48.3 s for madina_worldpop — a ~1,600× runtime advantage that the score’s log-scale penalty rewards. Accuracy-only ranking would put madina_worldpop first.</li>
<li><strong>Equilibrium helps on walk flows too.</strong> aequilibrae’s UE variants (log-log R² up to 0.155) beat its AoN baseline (0.084), though its BPR capacity model assumes vehicles and walk-mode results are therefore approximate (Limitations).</li>
<li><strong>The evidence base is thin:</strong> only 22 Telraam sensors matched the Leuven network, so all Leuven R² values are computed on a small sample.</li>
</ul>
</section>
<section id="driving-leeds-dft-aadt" class="level2">
<h2 class="anchored" data-anchor-id="driving-leeds-dft-aadt">Driving (Leeds, DfT AADT)</h2>
<p>Table <a href="#tbl-leeds" class="quarto-xref">Table&nbsp;3</a> reports the best variant per tool by efficiency score on Leeds drive flows, and Table <a href="#tbl-leeds-top3" class="quarto-xref">Table&nbsp;4</a> zooms into the top three variants of the best tool (cityseer_od).</p>
<div class="cell" data-execution_count="4">
<div id="tbl-leeds" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-leeds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Best variant per tool by efficiency score — Leeds, drive mode (DfT AADT ground truth). All seven tools are shown, sorted by efficiency score. R² rows for cityseer_od and aequilibrae use log-log R²; all other rows use linear R², so values are not directly comparable across rows. aequilibrae’s row is its all-or-nothing variant, which wins on speed even though UE fits better (see text).
</figcaption>
<div aria-describedby="tbl-leeds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Tool</th>
<th data-quarto-table-cell-role="th">Best variant</th>
<th data-quarto-table-cell-role="th">R²</th>
<th data-quarto-table-cell-role="th">Time (s)</th>
<th data-quarto-table-cell-role="th">Peak memory (MB)</th>
<th data-quarto-table-cell-role="th">Efficiency score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>cityseer_od</td>
<td>od_dimensionless_imp_centroid_tol0.03_r5000</td>
<td>0.1803</td>
<td>0.04</td>
<td>775.1</td>
<td>3.663</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>aequilibrae</td>
<td>aon</td>
<td>0.0827</td>
<td>0.21</td>
<td>375.7</td>
<td>0.388</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>flownet</td>
<td>aon_imp_ll</td>
<td>0.0601</td>
<td>5.53</td>
<td>403.8</td>
<td>0.028</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>sdna</td>
<td>MCF_euclidean_200m</td>
<td>0.1233</td>
<td>93.23</td>
<td>400.0</td>
<td>0.024</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>cityseer</td>
<td>bs_beta0.004_plain_ll</td>
<td>0.0125</td>
<td>0.82</td>
<td>773.6</td>
<td>0.017</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>madina</td>
<td>degree</td>
<td>0.0069</td>
<td>2.04</td>
<td>758.7</td>
<td>0.005</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>madina_worldpop</td>
<td>wp_r1200_beta001_all</td>
<td>0.0216</td>
<td>36.18</td>
<td>621.2</td>
<td>0.005</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="5">
<div id="tbl-leeds-top3" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-leeds-top3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Top three variants of the best-performing tool (cityseer_od) on Leeds drive flows, by efficiency score. All three use census OD demand with importance-weighted centroid dispersion.
</figcaption>
<div aria-describedby="tbl-leeds-top3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">R²</th>
<th data-quarto-table-cell-role="th">Time (s)</th>
<th data-quarto-table-cell-role="th">Peak memory (MB)</th>
<th data-quarto-table-cell-role="th">Efficiency score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>od_dimensionless_imp_centroid_tol0.03_r5000</td>
<td>0.1803</td>
<td>0.04</td>
<td>775.1</td>
<td>3.663</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>od_dimensionless_imp_centroid_tol0.03_r3000</td>
<td>0.1211</td>
<td>0.03</td>
<td>775.1</td>
<td>3.263</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>od_dimensionless_imp_centroid_tol0.0_r20000</td>
<td>0.1719</td>
<td>0.05</td>
<td>775.0</td>
<td>2.807</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Five findings stand out for drive flows:</p>
<ul>
<li><strong>Demand realism beats algorithm sophistication.</strong> cityseer_od with the real census OD matrix reaches log-log R² 0.180 at 0.04 s per run — an order of magnitude better than the synthetic gravity demand (madina_worldpop, 0.022) on the same network. The gap between demand inputs (0.022 → 0.180) dwarfs any algorithm-level difference measured here (see below).</li>
<li><strong>Dispersion beats tolerance, and both beat plain assignment.</strong> The top three cityseer_od variants (Table <a href="#tbl-leeds-top3" class="quarto-xref">Table&nbsp;4</a>) all use importance-weighted <em>centroid</em> dispersion at 3% tolerance: R² 0.180 at a 5 km radius. Dispersion around the OD centroid outperforms zone-based k-dispersion (best k3/k5/k10 R² 0.073–0.107), and tolerance effects saturate in the 2–5% range (tol 0.03 ≈ tol 0.0 at fixed radius; tol 0.05 slightly worse).</li>
<li><strong>User equilibrium beats all-or-nothing.</strong> aequilibrae’s UE (ue_bfw, log-log R² 0.096) beats its AoN baseline (0.083) — but AoN still wins inside aequilibrae by <em>efficiency</em> score, because UE costs ~1 s versus 0.12 s for roughly +0.01 R². This is exactly the accuracy–cost trade-off the efficiency score is designed to surface.</li>
<li><strong>The 10 km clip leaves its fingerprint.</strong> Zone-based k-dispersion reverses its full-region ranking inside the clip (Leeds k3 R² 0.073 &lt; centroid 0.180), and cityseer_od’s radius sweep (Figure <a href="#fig-dispersion" class="quarto-xref">Figure&nbsp;1</a>) plateaus from 8–40 km — the clip bounds the reachable network, so larger radii add nothing.</li>
<li><strong>flownet underperforms, and its PSL variants are not yet differentiated.</strong> All six flownet beta/detour variants returned identical R² (0.0039, ~500 s each), because the runner does not yet vary the path-sized-logit hyperparameters; its potential is therefore untested by these results. sDNA+ reaches the best <em>linear</em> R² among the non-demand tools (0.123, MCF 200 m) but takes ~93 s and its fit is dominated by high-flow links; per-segment observed-vs-predicted plots are not yet shown because the prediction exports are not aligned with the benchmark metric path (Limitations).</li>
</ul>
<div id="cell-fig-dispersion" class="cell" data-fig-dpi="150" data-fig-format="png" data-fig-height="3.6" data-fig-width="5" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-dispersion" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dispersion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dispersion-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="472" height="334">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dispersion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Radius sensitivity of cityseer_od on Leeds drive flows (census OD, centroid dispersion, 3% tolerance, log-log R²). Accuracy peaks at a 5 km radius (R² 0.180) and plateaus at ≈0.173 for radii of 8–40 km, consistent with the 10 km network clip bounding the reachable graph.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="cycling-coverage-gap-no-per-mode-sensor-data-yet" class="level2">
<h2 class="anchored" data-anchor-id="cycling-coverage-gap-no-per-mode-sensor-data-yet">Cycling (coverage gap — no per-mode sensor data yet)</h2>
<p>Cycle-flow estimates are conspicuously absent from the tables above, and the reason is data, not tooling. Both cities’ cycle networks are already generated (<code>data/leuven_cycle_edges.gpkg</code>, <code>data/leeds_cycle_edges.gpkg</code>, produced by the <code>generate_networks</code> stages) and every tool in the suite can run on them, but no per-mode cycle ground truth has been integrated yet: Telraam’s Leuven sensors are used for pedestrians, DfT’s AADT points for Leeds traffic, and neither provides matched cycle counts in the current data. Closing this gap is a priority — Telraam cycle counts and DfT cycle flow data are both candidate ground truths — and the suite needs only a sensors file and a <code>config/cities.yaml</code> entry to add the mode.</p>
</section>
<section id="efficiency-frontier" class="level2">
<h2 class="anchored" data-anchor-id="efficiency-frontier">Efficiency frontier</h2>
<p>Figure <a href="#fig-efficiency" class="quarto-xref">Figure&nbsp;2</a> plots every benchmarked variant — one point per variant — with runtime on a log x-axis and R² on the y-axis, for Leeds drive (left) and Leuven walk (right). The Pareto frontier of <em>fast and accurate</em> sits in the top-left: cityseer_od occupies it on both cities, combining the best fit with millisecond runtimes, while flownet anchors the opposite corner (~500 s for R² 0.004). The efficiency score is the single-number summary of this frontier: it ranks cityseer_od first in both cities precisely because it is the only tool that is both accurate and cheap.</p>
<div id="cell-fig-efficiency" class="cell" data-fig-dpi="150" data-fig-format="png" data-fig-height="4.4" data-fig-width="10" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-efficiency" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-efficiency-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="953" height="411">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Efficiency frontier: runtime (log x-axis) versus R² for every benchmarked variant, coloured by tool. Left: Leeds drive (log-log R² for cityseer_od and aequilibrae, linear R² otherwise). Right: Leuven walk (same metric split). Best-per-tool variants are labelled. The Pareto frontier of fast + accurate sits top-left; cityseer_od occupies it on both cities, flownet the bottom-right.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="accuracy-versus-complexity" class="level2">
<h2 class="anchored" data-anchor-id="accuracy-versus-complexity">Accuracy versus complexity</h2>
<p>Figure <a href="#fig-complexity" class="quarto-xref">Figure&nbsp;3</a> places each tool family by its source-code size (log x-axis) and the best R² it achieves on Leeds drive flows, coloured by the efficiency score of that best variant. The headline: the cityseer family — 8.7k lines of Python (Rust core excluded) plus a ~1.4k-line integration, including a small OD-assignment script — delivers the best fit (log-log R² 0.180) at 0.04 s, while aequilibrae’s 16.2k-line codebase reaches 0.096 at ~1 s and sDNA+’s 17.2k-line C++ reaches linear R² 0.123 at ~93 s. flownet’s 1.8k lines are the cheapest to read but the most expensive to run (~500 s) for the weakest fit. Efficiency — accuracy per unit of compute — correlates with <em>small</em> codebases here, not large ones.</p>
<div id="cell-fig-complexity" class="cell" data-fig-dpi="150" data-fig-format="png" data-fig-height="4.6" data-fig-width="6.5" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-complexity" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-complexity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-complexity-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="602" height="428">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-complexity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Accuracy versus complexity on Leeds drive flows: tool source LoC (log x-axis) versus the best R² achieved by that tool family (max over variants), labelled by the best-performing member. Open markers: log-log R² (cityseer_od, aequilibrae); filled: linear R². Colour: efficiency score of the labelled variant. cityseer’s Rust core and aequilibrae’s C++ core are excluded from the Python LoC counts.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p><strong>Q1 — The route-choice model class matters, but modestly.</strong> On Leeds drive flows, dispersed and equilibrium assignment consistently beat the AoN baseline: aequilibrae UE (log-log R² 0.096) beats AoN (0.083), and cityseer_od’s dispersed centroid assignment (0.180) beats its plain shortest-path variant (0.074). Dispersion around the OD centroid matters more than the tolerance setting, which saturates in the 2–5% range. But the most sophisticated class in the suite — flownet’s path-sized logit — shows no signal yet: all six variants returned identical predictions (a runner limitation, not evidence against PSL), so the ceiling of the model-class ladder remains untested.</p>
<p><strong>Q2 — Demand realism dominates algorithm sophistication.</strong> The single largest effect in the benchmark is the demand input. On Leeds, replacing synthetic gravity demand with the real census OD matrix moves log-log R² from 0.022 (madina_worldpop) to 0.180 (cityseer_od) — an eightfold improvement — while the largest algorithm-level effect measured (UE vs AoN) moves R² by only ~0.01. On Leuven walk flows, the pattern inverts in spirit: the gravity demand model explains most of the variance (linear R² 0.68–0.88) because pedestrian counts around Leuven are well predicted by population and POI attractors, and pure centrality explains almost nothing. Demand realism matters most where demand drives the model — and it matters more than the assignment algorithm everywhere.</p>
<p><strong>Q3 — The efficiency score changes the rankings.</strong> An accuracy-only ranking would lead with madina_worldpop on Leuven (R² 0.876) and cityseer_od on Leeds (0.180). The efficiency score reorders both cities: cityseer_od wins Leuven too (3.07 vs 0.21 for madina_worldpop, a ~1,600× runtime gap), and inside aequilibrae the AoN variant outranks UE despite fitting worse, because UE buys +0.01 R² at ~10× the runtime. flownet drops to last place everywhere: ~500 s per run for R² 0.004. The frontier figure (Figure <a href="#fig-efficiency" class="quarto-xref">Figure&nbsp;2</a>) makes the trade-off visible: the top-left corner belongs to tools that are both accurate and cheap, which is the combination that matters for city-scale application.</p>
<p><strong>Complexity-adjusted comparison.</strong> The complexity figure (Figure <a href="#fig-complexity" class="quarto-xref">Figure&nbsp;3</a>) tempers the headline ranking. Aequilibrae’s 16.2k lines of source deliver roughly +0.01 R² over the cityseer family’s 8.7k lines at the assignment level, and cityseer’s Rust core is deliberately excluded from its Python LoC — so apparent differences in code size overstate differences in engineering effort. Whether the extra machinery is worthwhile depends on the application: production traffic models need aequilibrae’s equilibrium and matrix tools; rapid screening may not.</p>
<p><strong>Mode coverage.</strong> Results are limited to walk (Leuven) and drive (Leeds); cycle flows await sensor data, with the networks and tooling already in place (Results — Cycling). Rankings are mode-dependent: madina_worldpop leads accuracy on Leuven walk but sits near the bottom on Leeds drive, which is exactly why per-mode benchmarking matters.</p>
</section>
<section id="limitations" class="level1">
<h1>Limitations</h1>
<ul>
<li><strong>R² metric mismatch across cities and tools</strong>: linear R² is used for Leuven Telraam walk counts and for all centrality/gravity tools, while log-log R² is used for Leeds AADT and for the cityseer_od and aequilibrae rows in both tables; R² values are therefore not directly comparable across rows, tables or cities. The metrics helpers (<code>compute_metrics</code> vs <code>compute_metrics_loglog</code>) should report both scales in future runs.</li>
<li><strong>Single city per mode so far</strong>: walk is only benchmarked in Leuven and drive only in Leeds, so tool rankings may not generalise across urban contexts.</li>
<li><strong>Leeds clip boundary artefact</strong>: the 10 km buffer clip around central Leeds breaks zone-based k-dispersion, reversing the k3 vs centroid ranking seen on the full region, and caps the effective dispersion radius at the clip extent (Figure <a href="#fig-dispersion" class="quarto-xref">Figure&nbsp;1</a>).</li>
<li><strong>flownet is not yet exercised</strong>: its demand is synthetic everywhere, and its PSL beta/detour hyperparameters were not varied by the runner, so all six variants returned identical predictions; the path-sized-logit model class is consequently untested by these results.</li>
<li><strong>Demand and mode approximations</strong>: aequilibrae’s walk-mode assignment is an approximation (the BPR capacity model assumes vehicles; the AoN baseline is unaffected).</li>
<li><strong>Small sensor samples</strong>: 22 matched Telraam sensors in Leuven and 181–197 matched AADT links in Leeds (where recorded) bound the statistical power of every R² here.</li>
<li><strong>Per-segment prediction exports are not yet aligned with the benchmark metric path</strong>: the <code>results/*_best_predictions.csv</code> files are produced by different code paths (interactive-map and sDNA+ runners) than the metrics in the result tables and are stale relative to the current results, so observed-vs-predicted plots are omitted from this paper until the export paths are aligned with the <code>compute_metrics</code> pipeline.</li>
</ul>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>These results invite extension rather than conclusion. The three questions answered here — route-choice model class matters modestly, demand realism dominates algorithm choice, and the efficiency score reorders the ranking — each deserve more cities, more modes and more tools. Oxford is a candidate city, cycle counts are the obvious missing mode (the networks and tooling are ready), and flownet’s PSL class needs a runner that varies its hyperparameters before its model class can be judged. The suite is designed to make this cheap: a new city needs a <code>config/cities.yaml</code> entry, ground-truth and demand preparation scripts, and a per-tool runner — contributions to the cenbench repository are welcome.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-aequilibrae2024" class="csl-entry" role="listitem">
Camargo, Pedro. 2024. <span>“AequilibraE: Open-Source Transportation Modeling.”</span> <a href="https://aequilibrae.com">https://aequilibrae.com</a>.
</div>
<div id="ref-cooper2020sdna" class="csl-entry" role="listitem">
Cooper, Crispin H. V., and Alain J. F. Chiaradia. 2020. <span>“sDNA: 3-d Spatial Network Analysis for <span>GIS</span>, <span>CAD</span>, <span>Command</span> <span>Line</span> &amp; <span>Python</span>.”</span> <em>SoftwareX</em> 12 (July): 100525. <a href="https://doi.org/10.1016/j.softx.2020.100525">https://doi.org/10.1016/j.softx.2020.100525</a>.
</div>
<div id="ref-dft2023aadt" class="csl-entry" role="listitem">
Department for Transport. 2023. <span>“Road Traffic Statistics: Annual Average Daily Traffic (<span>AADT</span>).”</span> <a href="https://roadtraffic.dft.gov.uk/">https://roadtraffic.dft.gov.uk/</a>.
</div>
<div id="ref-krantz2024flownet" class="csl-entry" role="listitem">
Krantz, Sebastian, Robert Dünch, et al. 2024. <span>“Flownet: Flow-Aware and Multimodal Transport Network Analysis in <span>R</span>.”</span> <em>Journal of Statistical Software</em>. <a href="https://sebkrantz.github.io/flownet/">https://sebkrantz.github.io/flownet/</a>.
</div>
<div id="ref-sevtsuk2025madina" class="csl-entry" role="listitem">
Sevtsuk, Andres, and Abdulaziz Alhassan. 2025. <span>“Madina Python Package: Scalable Urban Network Analysis for Modeling Pedestrian and Bicycle Trips in Cities.”</span> <em>Journal of Transport Geography</em> 123 (February): 104130. <a href="https://doi.org/10.1016/j.jtrangeo.2025.104130">https://doi.org/10.1016/j.jtrangeo.2025.104130</a>.
</div>
<div id="ref-simons2022cityseer" class="csl-entry" role="listitem">
Simons, Gareth. 2022. <span>“The Cityseer Python Package for Pedestrian-Scale Network-Based Urban Analysis.”</span> <em>Environment and Planning B: Urban Analytics and City Science</em> 50 (5): 1328–44. <a href="https://doi.org/10.1177/23998083221133827">https://doi.org/10.1177/23998083221133827</a>.
</div>
<div id="ref-telraam2024" class="csl-entry" role="listitem">
Telraam. 2024. <span>“Telraam API Documentation.”</span> <a href="https://telraam-api.net">https://telraam-api.net</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>